backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "settings"
    label: "Profile Settings"
    files:
      - label: "Profile"
        name: "profile"
        file: "data/profile.json"
        fields:
          - {label: "Username", name: "username", widget: "string"}
          - {label: "Biography", name: "bio", widget: "string"}
          - {label: "Avatar", name: "avatar", widget: "image", required: false}

  - name: "links_collection"
    label: "Social Links"
    files:
      - label: "Links"
        name: "links_data"
        file: "data/links.json"
        fields:
          - label: "Links"
            name: "links"
            widget: "list"
            fields:
              - {label: "Platform Name", name: "title", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
              - {label: "Visible", name: "visible", widget: "boolean", default: true}
              - {label: "Order", name: "order", widget: "number", default: 0}
